### ISSUE TITLE
[Bug] handle causes ArithmeticException due to improper detailsInterval value checking

### ISSUE THREAD

**Issue by moonlightingLL** [xlab-uiuc/confuzz#167]
## What happened
There is no value checking for parameter `yarn.dispatcher.print-events-info.threshold`. This may cause improper calculations and crashes the system like division by 0.

## Buggy code
In `AsyncDispatcher.java`, there is no value checking for `detailsInterval ` which is passed directly to `handle` method. When `detailsInterval ` is mistakenly set to 0, the code would cause division by 0 and throw ArithmeticException to crash the system.

```java
  protected void serviceInit(Configuration conf) throws Exception{
    super.serviceInit(conf);
    this.detailsInterval = getConfig().getInt(YarnConfiguration.
                    YARN_DISPATCHER_PRINT_EVENTS_INFO_THRESHOLD,
            YarnConfiguration.
                    DEFAULT_YARN_DISPATCHER_PRINT_EVENTS_INFO_THRESHOLD);
  }
...
public void handle(Event event) {
...
      if (qSize != 0 && qSize % detailsInterval == 0
              && lastEventDetailsQueueSizeLogged != qSize) {
      }
...
}
```
###How to reproduce
set `yarn.dispatcher.print-events-info.threshold`=`0`
run `org.apache.hadoop.yarn.event.TestAsyncDispatcher#testDispatcherMetricsHistogram`

For an easy reproduction, run the reproduce.sh in the attachment.
```
repo=hadoop
sha=680af873777f7fce0224781b9ecc547f8f8ded77
module=hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common
test="org.apache.hadoop.yarn.event.TestAsyncDispatcher#testDispatcherMetricsHistogram"
file="target/classes/core-site.xml"
name="yarn.dispatcher.print-events-info.threshold"
value=0

# inject
inject() {
    echo "<configuration><property><name>$name</name><value>$value</value></property></configuration>" > $file
}

# 1. Clone the repo and checkout
# 2. Build module and setup configuration
# 3. Run test
git clone git@github.com:apache/$repo \
    && cd $repo && git checkout $sha \
    && mvn install -DskipTests -pl $module -am \
    && cd $module && inject \
    && mvn surefire:test -Dtest=$test
```
We are happy to provide a patch if this issue is confirmed.

**Comment by moonlightingLL** [comment]
Someone has already open it.

**Comment by darko-marinov** [comment]
> Someone has already open it.

Did one of our collaborators open the issue, or was it done by someone we don't know at all?

@shuaiwang516 and @hwang-pku have you coordinated with everyone to avoid duplicating work?

**Comment by hwang-pku** [comment]
I guess Nancy means that someone opened it in the github issue of this project. I designed a "Lock" mechanism but it seems  the mechanism did not work. We will make sure on slack that if anyone is going to change/open/work on anything they should report it on slack first to avoid duplicating work.

**Comment by tianyin** [comment]
ad hoc synchronization considered harmful :)
